services:
  vue:
    image: ${VUE_WEB_IMAGE_NAME:-xcy960815/study-java-vue}:${VUE_WEB_IMAGE_VERSION:-latest}
    container_name: study-java-vue-container
    ports:
      - '${VUE_WEB_PORT:-80}:80'
    environment:
      - TZ=${TIMEZONE:-Asia/Shanghai}
    networks:
      - study-java-network
    logging:
      driver: json-file
      options:
        max-size: '${LOG_MAX_SIZE:-10m}'
        max-file: '${LOG_MAX_FILE:-3}'
    restart: always

networks:
  study-java-network:
    external: true
    name: ${DOCKER_NETWORK_NAME:-study-java-network}
